server:
  port: 9192
spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  file: C:/Users/alberto/microservice.log